// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK0d8nXTKkrs5Ixjx8_eI4bZPIQ2aww0A',
    appId: '1:1036702358315:web:fa44a5cfcfc6597cc2c36e',
    messagingSenderId: '1036702358315',
    projectId: 'restup-379016',
    authDomain: 'restup-379016.firebaseapp.com',
    storageBucket: 'restup-379016.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPYf-QpME-H9p3672S-0yR_RzPxaUi6CE',
    appId: '1:1036702358315:android:dbb3476f23c5bf07c2c36e',
    messagingSenderId: '1036702358315',
    projectId: 'restup-379016',
    storageBucket: 'restup-379016.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN2-HhRmIdAX-SkqVZjS_BfYwQfVsDrCU',
    appId: '1:1036702358315:ios:c2a93f893edab9ecc2c36e',
    messagingSenderId: '1036702358315',
    projectId: 'restup-379016',
    storageBucket: 'restup-379016.appspot.com',
    iosClientId: '1036702358315-a9cu4i7r655n9a40dfmql6sln120jh37.apps.googleusercontent.com',
    iosBundleId: 'com.example.restUpFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN2-HhRmIdAX-SkqVZjS_BfYwQfVsDrCU',
    appId: '1:1036702358315:ios:c2a93f893edab9ecc2c36e',
    messagingSenderId: '1036702358315',
    projectId: 'restup-379016',
    storageBucket: 'restup-379016.appspot.com',
    iosClientId: '1036702358315-a9cu4i7r655n9a40dfmql6sln120jh37.apps.googleusercontent.com',
    iosBundleId: 'com.example.restUpFlutter',
  );
}
